name: Test deploy on Azure 

on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: greatapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        file-url: 'https://dptestdeploy.blob.core.windows.net/test/publish.zip'
    - run: ls
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish.zip'
