name: Test deploy on Azure 

on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: testwebappxz    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  deploy:
    runs-on: windows-latest
    steps:

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
    - run: azcopy_v10 "https://dptestdeploy.blob.core.windows.net/test/publish.zip" ".\publish.zip"
    - run: |
          dir
          cd ..
          dir
          cd ..
          dir
          cd ..
          dir
    - run: pwd
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish.zip'
