name: Test deploy on Azure 

on: 
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: greatapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Virtual path settings'
      run: |
       az resource update --name "wbtest110118/config/web" --resource-group "wbtest110118" --resource-type "Microsoft.Web/sites/config" --set "properties.virtualApplications=[\{\"virtualPath\":\"\/\",\"physicalPath\":\"site\\wwwroot\",\"virtualDirectories\":null\},\{\"virtualPath\":\"\/api\",\"physicalPath\":\"site\\wwwroot\\api\",\"virtualDirectories\":null\},\{\"virtualPath\":\"\/report\",\"physicalPath\":\"site\\wwwroot\\report\",\"virtualDirectories\":null\}]"
