name: 'Deploy db as container reusable'

on:
  workflow_call:
    inputs:
      withresourcegroumname:
        description: 'Resource group name where container will be placed'
        required: true
        type: string
      withcontainerinstancename:
        description: 'Container instance name that will be used in dns name of container'
        required: true
        type: string
      withdbcontainername:
        description: 'If the db other than empty is required. Default: empty'
        required: false
        type: string
      withdbcontainerversion:
        description: 'If the specific version of db is required. Default: latest'
        required: false
        type: string
      withregion:
        description: 'Location of the container. Default: west europe'
        required: false
        type: string
    secrets:
      DB_USERID:
        required: true
      DB_PASSWORD:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      AZURE_CREDENTIALS:
        required: true
    outputs:
      sqlconnectionstr:
        description: 'Connection string'
        value: ${{ jobs.create_db_container.outputs.connectionstring}}
jobs:
  create_db_container:
    name: 'Create database container'
    runs-on: ubuntu-latest 
    env:
      container_version:  ${{ inputs.withdbcontainerversion == '' && 'latest' ||  inputs.withdbcontainerversion  }} 
      container_name: ${{ inputs.withdbcontainername == '' && 'empty' ||  inputs.withdbcontainername  }}
      container_location: ${{ inputs.withregion == '' && 'west europe' ||  inputs.withregion  }}
    outputs:
      connectionstring: ${{ format('Server=tcp:{0}.westeurope.azurecontainer.io,1433;Initial Catalog=wbdatabase;Persist Security Info=False;User ID={1};Password={2};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;', inputs.withcontainerinstancename, secrets.DB_USERID, secrets.DB_PASSWORD)}}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{inputs.withresourcegroumname}}
        dns-name-label: ${{inputs.withcontainerinstancename}}
        image: ${{ format('wbdevcr.azurecr.io/databases/{0}:{1}', env.container_name, env.container_version)  }} 
        ports: 1433
        cpu: 2   #Optional
        memory: 8   #Optional
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{inputs.withcontainerinstancename}}
        location: ${{env.container_location}} 