name: 'POC deploy'

on:
  workflow_dispatch:
    inputs:
      buildnumber:
        description: 'Build number'
        required: true
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  deploy_app:
    name: 'Deploy on Azure on slot'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:     
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-artifact
      with:
        file-url: 'https://${{ secrets.ACCOUNT_NAME }}.blob.core.windows.net/${{ secrets.ARTIFACTS_PATH }}/${{ github.event.inputs.buildnumber }}/WorkBookv9.zip?sv=${{ secrets.ACCOUNT_SAS }}'
    - name: Azure Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy using az'
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 1800
        max_attempts: 5
        retry_on: error
        command: az webapp deploy --name wbtest${{ github.event.inputs.buildnumber }} --resource-group wbtest${{ github.event.inputs.buildnumber }} --src-path '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WorkBookv9.zip' --type zip --slot test
